### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Ying-yin11** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#3]
Download the videos [here](https://drive.google.com/drive/u/1/folders/0B5peJ1MHnIWGd3pFbzMyTG5BSGs).(offical)关于这个链接，我点不开，请问您有其他访问的方式吗？
修改opts.py文件中一处目录，为Emotion_REC所在绝对路径，已进行注释。您这里的提到Emotion_REC在哪里呀，我没有找到。

**Comment by Robin-WZQ** [comment]
您好！针对链接打不开的问题，可能是需要搭梯子才能访问，因为作者是将数据存放在谷歌云盘上了。我找到了我当时的数据集，包括原始数据和已经弄好切分成图片的数据集，放在百度云盘上了。如果你是想用这个DEMO的话，不用下载数据，用我训练好的模型就行，我也提供了百度云下载链接。这里的Emotion_REC是指整个项目名（已对教程修改），你就把opts.py文件中的第19行改成这个大文件目录所在绝对路径就ok了。感谢提问！

**Comment by leellfly** [comment]
你好，谷歌云盘上的数据集可以帮忙开通权限么？或者有没有百度云的链接可以下载数据集呢，求看看～

**Comment by Robin-WZQ** [comment]
您好，我用到的数据都在主页的preparation中提供了百度网盘的下载链接，目前我看了下可以下载。然后谷歌网盘的话我试了，实在太慢了，也没有找到很好的加速方法。








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月19日(星期三) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Robin-WZQ/multimodal-emotion-recognition-DEMO] 求助 (Issue #3)





 
你好，谷歌云盘上的数据集可以帮忙开通权限么？或者有没有百度云的链接可以下载数据集呢，求看看～
