### ISSUE TITLE
请问AVL视频解码器具体是什么

### ISSUE THREAD

**Issue by Peng-jpg** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#4]
同学你好，请问这个解码器是一个python包还是一个应用程序呢，如果你能提供一下下载网址那就更好了😘

**Comment by Robin-WZQ** [comment]
非常抱歉回复地迟了些，因为时间有些长已经忘了AVL是什么了，所以这一周又把代码翻出来在新的电脑上尝试复现。首先，AVL是完全不必要的，当时可能是和别的东西搞混了。其次，我更新了教程，将所有文件都打包到了百度云，同时写了一份说明文档，理论上按照其安装就不会有问题（已在另一台全新电脑上运行成功）。

**Comment by Peng-jpg** [comment]
没关系，我尝试看懂了你的代码的一部分，因为我的毕业设计选题与此项目有关；至于AVL视频播放器，我想可能是因为Pyqt5的Widget空间提升成Qvideowidget后，Mp4文件必须要被解码为AVL文件才能播放，详情可见https://clay-atlas.com/blog/2019/11/11/python-chinese-directshowplayerservicedorender-unresolved-error-code-0x8040266-idisspatch-error-102/，而这个下载的解码器是默认运行在后台无需调用的，即使你把项目重新跑一遍也发现不了这个大小几兆的解码器，所以这可能是你不知道你当初为什么写AVL解码器的原因，，，抱歉这么一个小问题让你这几天又回来重新跑这个项目。。🤥🤥🤥

**Comment by Robin-WZQ** [comment]
@Peng-jpg 十分感谢！！！
