### ISSUE TITLE
Models Links

### ISSUE THREAD

**Issue by e-hosseini** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#5]
Hi,
It's impossible to download the model linked (like `save_30.pth`) from the posted links as the host doesn’t allow registering for other counties' phones!!!

Can you please upload them somewhere else like google?

**Comment by Robin-WZQ** [comment]
ok, i will do it as soon as possible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Robin-WZQ/multimodal-emotion-recognition-DEMO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 凌晨0:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Robin-WZQ/multimodal-emotion-recognition-DEMO] Models Links (Issue #5)





 
Hi,
 It's impossible to download the model linked (like save_30.pth) from the posted links as the host doesn’t allow registering for other counties' phones!!!
 
Can you please upload them somewhere else like google?
