### ISSUE TITLE
测试准确度不太理想

### ISSUE THREAD

**Issue by She-yh** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#6]
感谢同学分享
因最近在做Web端的多模态情感识别，找了很久终于找到了你的开源仓库。因为我是新手，代码很有帮助，写的文档也很细，感谢分享。
但是我用MELD数据集的原始视频测了一下 准确度不太行。
看你也没有维护了就不麻烦了，如果今后有机会一起交流。
祝学业顺利

**Comment by Robin-WZQ** [comment]
嗯嗯谢谢祝福！
您也加油！
