### ISSUE TITLE
main.py实验时不会返回情感结果

### ISSUE THREAD

**Issue by 123hello3** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#7]
你好，想应用模型直接进行情感分析，但在实验时发现在main.py中对于选取的视频进行情感分析时不会返回结果，请问这是什么原因，谢谢

**Comment by Robin-WZQ** [comment]
@123hello3 您好！如果是运行demo的话请运行Emotion.py，如果是直接进行视频推断请参考原始项目主页提供的[代码](https://github.com/maysonma/VAANet)

**Comment by 123hello3** [comment]
您好，请问原始项目主页提供的代码是否可以直接对于任意视频进行情感分析呢

**Comment by Robin-WZQ** [comment]
@123hello3 印象中只能对数据集中的视频类型进行分类，但我不是研究这个方向，不知道现在学界和工业界是否已有支持任意长度任意分辨率下的工作。在本项目中，我们是每t秒对电脑记录的视频和音频进行截断，并合成VAANET需要的输入格式进行推断。

**Comment by 123hello3** [comment]
感谢回复！因为想借用vaanet这个模型进行任意一个短视频的情感分析以完成一项课程设计，但由于找不到应该加入本地音视频输入位置等问题而遇到瓶颈，所以想请问您是否可以给出一些改进办法或意见，感激不尽！







                       
原始邮件
                       
                     

发件人："Robin-WZQ"< ***@***.*** &gt;;

发件时间：2024/3/15 9:26

收件人："Robin-WZQ/multimodal-emotion-recognition-DEMO"< ***@***.*** &gt;;

抄送人："123hello3"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [Robin-WZQ/multimodal-emotion-recognition-DEMO] main.py实验时不会返回情感结果 (Issue #7)




 
@123hello3 印象中只能对数据集中的视频类型进行分类，但我不是研究这个方向，不知道现在学界和工业界是否已有支持任意长度任意分辨率下的工作。在本项目中，我们是每t秒对电脑记录的视频和音频进行截断，并合成VAANET需要的输入格式进行推断。

**Comment by Robin-WZQ** [comment]
@123hello3 您好！抱歉我理解错您的意思了，您是要做一个test的接口是吧，我以为您说的任意视频是指任意分辨率和任意长度。关于这个我们确实是在开源代码中实现了这个接口，应该是main.py里面output_result(path)函数能搞定。但这是我们debug使用的所以demo里面不会调用，关于详细使用可以在阅读源码的基础上进行修改。或者改写VAANET里面的代码，毕竟train和test没啥大区别

**Comment by 123hello3** [comment]
感谢回复！我是要做一个对于爬取视频的情绪识别，我尝试过使用main.py中的output_result(path)函数，但是会出现找不到指定视频，导致根本没有结果输出的情况，类似于图片的情况



                       
原始邮件
                       
                     

发件人："Robin-WZQ"< ***@***.*** &gt;;

发件时间：2024/3/22 15:36

收件人："Robin-WZQ/multimodal-emotion-recognition-DEMO"< ***@***.*** &gt;;

抄送人："123hello3"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [Robin-WZQ/multimodal-emotion-recognition-DEMO] main.py实验时不会返回情感结果 (Issue #7)




 
@123hello3 您好！抱歉我理解错您的意思了，您是要做一个test的接口是吧，我以为您说的任意视频是指任意分辨率和任意长度。关于这个我们确实是在开源代码中实现了这个接口，应该是main.py里面output_result(path)函数能搞定。但这是我们debug使用的所以demo里面不会调用，关于详细使用可以在阅读源码的基础上进行修改。或者改写VAANET里面的代码，毕竟train和test没啥大区别

**Comment by Robin-WZQ** [comment]
@123hello3 嗯嗯，因为这个功能不是本项目的目标，这个需要您自行来修改源码定位错误了，印象里并不复杂，祝好运！
