### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xie-20** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#9]
Video_main 录视频很多时候会显示    os.remove("temp.wav") # 删除中间音频文件
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'temp.wav' 有时候又能录上 很奇怪

**Comment by Robin-WZQ** [comment]
@xie-20 您好，这个看一下是不是路径有中文，或者没有全部改对您那边的路径导致的？之前没遇到过类似报错
